version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: web/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/news_db
    volumes:
      - ./web:/app/web
      - ./config:/app/config
      - ./shared:/app/shared

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=news_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
