categories:
  - id: 1
    name: Политика
    slug: politics
  - id: 2
    name: Спорт
    slug: sports
  - id: 3
    name: Технологии
    slug: tech
  - id: 4
    name: Культура
    slug: culture
  - id: 5
    name: Экономика
    slug: economy
